[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "din6892"
version = "0.1.0"
description = "Implementation of DIN 6892 - Drive type fastenings without taper action - Parallel keys - Calculation and design"
readme = "README.md"
license = {file = "LICENSE.txt"}
authors = [{name = "hanslhansl", email = "p4u1_1@posteo.at"}]
dependencies = [
    "din6885 @ git+https://github.com/hanslhansl/din6885.git"
]

[tool.setuptools]
packages = ["din6892"]